l=(function(url) {
    return "http://www.boomlings.com/database"+url;
});
u={
    URL_BLOCK_USER: '/blockGJUser20.php',
    URL_UNBLOCK_USER: '/unblockGJUser20.php',
    URL_RATE_LEVEL_STARS: '/rateGJStars211.php',
    URL_RATE_LEVEL_DEMON: '/rateGJDemon21.php',
    URL_UPLOAD_LEVEL: '/uploadGJLevel21.php',
    URL_SUGGEST_LEVEL_STARS: '/suggestGJStars20.php',
    URL_GET_USER_INFO: '/getGJUserInfo20.php',
    URL_USER_SEARCH: '/getGJUsers20.php',
    URL_GET_USER_TOP: '/getGJScores20.php',
    URL_UPDATE_USER_SCORE: '/updateGJUserScore22.php',
    URL_GET_LEVEL_SCORES: '/getGJLevelScores211.php',
    URL_REPORT_LEVEL: '/reportGJLevel.php',
    URL_DOWNLOAD_LEVEL: '/downloadGJLevel22.php',
    URL_LEVEL_SEARCH: '/getGJLevels21.php',
    URL_UPDATE_LEVEL_DESC: '/updateGJDesc20.php',
    URL_GET_MAPPACKS: '/getGJMapPacks21.php',
    URL_GET_GAUNTLETS: '/getGJGauntlets21.php',
    URL_DELETE_LEVEL: '/deleteGJLevelUser20.php',
    URL_GET_SONG_INFO: '/getGJSongInfo.php',
    URL_GET_USER_LIST: '/getGJUserList20.php',
    URL_REMOVE_FRIEND: '/removeGJFriend20.php',
    URL_GET_ACC_COMMENTS: '/getGJAccountComments20.php',
    URL_GET_COMMENTS: '/getGJComments21.php',
    URL_GET_PRIVATE_MESSAGES: '/getGJMessages20.php',
    URL_READ_PRIVATE_MESSAGE: '/downloadGJMessage20.php',
    URL_SEND_PRIVATE_MESSAGE: '/uploadGJMessage20.php',
    URL_DELETE_PRIVATE_MESSAGE: '/deleteGJMessages20.php',
    URL_GET_TIMELY: '/getGJDailyLevel.php',
    URL_LOGIN: '/accounts/loginGJAccount.php',
    URL_SAVE_DATA: '/accounts/backupGJAccountNew.php',
    URL_LOAD_DATA: '/accounts/syncGJAccountNew.php',
    URL_MANAGE_ACCOUNT: '/accounts/accountManagement.php',
    URL_CHANGE_PASSWORD: '/accounts/changepassword.php',
    URL_CHANGE_USERNAME: '/accounts/changeusername.php',
    URL_DELETE_ACC_COMMENT: '/deleteGJAccComment20.php',
    URL_DELETE_LEVEL_COMMENT: '/deleteGJComment20.php',
    URL_UPLOAD_COMMENT: '/uploadGJComment21.php',
    URL_UPLOAD_ACC_COMMENT: '/uploadGJAccComment20.php',
    URL_GET_FRIEND_REQUESTS: '/getGJFriendRequests20.php',
    URL_READ_REQUEST: '/readGJFriendRequest20.php',
    URL_DELETE_REQUEST: '/deleteGJFriendRequests20.php',
    URL_ACCEPT_REQUEST: '/acceptGJFriendRequest20.php',
    URL_SEND_REQUEST: '/uploadFriendRequest20.php',
    URL_REQUEST_MODERATOR: '/requestUserAccess.php',
    URL_GET_COMMENT_HISTORY: '/getGJCommentHistory.php',
    URL_GET_ACCOUNT_URL: '/getAccountURL.php',
    URL_LIKE_ITEM: '/likeGJItem211.php',
    URL_TEST_SONG: '/testSong.php'
}

module.exports = { load:l, url:u };