module.exports = { 
    load: function(url) {
        return "http://www.boomlings.com/database"+url;
    },

    BLOCK_USER: '/blockGJUser20.php',
    UNBLOCK_USER: '/unblockGJUser20.php',
    RATE_LEVEL_STARS: '/rateGJStars211.php',
    RATE_LEVEL_DEMON: '/rateGJDemon21.php',
    UPLOAD_LEVEL: '/uploadGJLevel21.php',
    SUGGEST_LEVEL_STARS: '/suggestGJStars20.php',
    GET_USER_INFO: '/getGJUserInfo20.php',
    USER_SEARCH: '/getGJUsers20.php',
    GET_USER_TOP: '/getGJScores20.php',
    UPDATE_USER_SCORE: '/updateGJUserScore22.php',
    GET_LEVEL_SCORES: '/getGJLevelScores211.php',
    REPORT_LEVEL: '/reportGJLevel.php',
    DOWNLOAD_LEVEL: '/downloadGJLevel22.php',
    LEVEL_SEARCH: '/getGJLevels21.php',
    UPDATE_LEVEL_DESC: '/updateGJDesc20.php',
    GET_MAPPACKS: '/getGJMapPacks21.php',
    GET_GAUNTLETS: '/getGJGauntlets21.php',
    DELETE_LEVEL: '/deleteGJLevelUser20.php',
    GET_SONG_INFO: '/getGJSongInfo.php',
    GET_USER_LIST: '/getGJUserList20.php',
    REMOVE_FRIEND: '/removeGJFriend20.php',
    GET_ACC_COMMENTS: '/getGJAccountComments20.php',
    GET_COMMENTS: '/getGJComments21.php',
    GET_PRIVATE_MESSAGES: '/getGJMessages20.php',
    READ_PRIVATE_MESSAGE: '/downloadGJMessage20.php',
    SEND_PRIVATE_MESSAGE: '/uploadGJMessage20.php',
    DELETE_PRIVATE_MESSAGE: '/deleteGJMessages20.php',
    GET_TIMELY: '/getGJDailyLevel.php',
    LOGIN: '/accounts/loginGJAccount.php',
    SAVE_DATA: '/accounts/backupGJAccountNew.php',
    LOAD_DATA: '/accounts/syncGJAccountNew.php',
    MANAGE_ACCOUNT: '/accounts/accountManagement.php',
    CHANGE_PASSWORD: '/accounts/changepassword.php',
    CHANGE_USERNAME: '/accounts/changeusername.php',
    DELETE_ACC_COMMENT: '/deleteGJAccComment20.php',
    DELETE_LEVEL_COMMENT: '/deleteGJComment20.php',
    UPLOAD_COMMENT: '/uploadGJComment21.php',
    UPLOAD_ACC_COMMENT: '/uploadGJAccComment20.php',
    GET_FRIEND_REQUESTS: '/getGJFriendRequests20.php',
    READ_REQUEST: '/readGJFriendRequest20.php',
    DELETE_REQUEST: '/deleteGJFriendRequests20.php',
    ACCEPT_REQUEST: '/acceptGJFriendRequest20.php',
    SEND_REQUEST: '/uploadFriendRequest20.php',
    REQUEST_MODERATOR: '/requestUserAccess.php',
    GET_COMMENT_HISTORY: '/getGJCommentHistory.php',
    GET_ACCOUNT_URL: '/getAccountURL.php',
    LIKE_ITEM: '/likeGJItem211.php',
    TEST_SONG: '/testSong.php'
};